fix README comment; add err func & param check to precommit;

diff --git a/_hooks/pre-commit b/_hooks/pre-commit
--- a/_hooks/pre-commit
+++ b/_hooks/pre-commit
@@ -1,21 +1,26 @@
 #!/bin/bash
-#
 
-# A git hook script that runs the same checks that are 
-# executed on Travis to verify your commits will not fail.
-# Bypass it with the --no-verify option to git-commit
+# A git hook script that runs the same checks that are executed on Travis to
+# verify your commits will not fail. Bypass it with the --no-verify option to
+# git commit
 #
 # usage: make a symlink to this file,
 # e.g., rm -rf .git/hooks/ && ln -s -f ../_hooks .git/hooks
 
-# Run 
-./_tests/travis-checks.sh --disable-external
+#######################################
+# Error function to display error message to end users.
+# Arguments:
+#   Error message description
+#######################################
+err() {
+  echo "$@"
+  exit 1
+}
+
+./_tests/travis-checks --quick
 
 if [ $? -eq 0 ]; then
-    exit 0
+  exit 0
 else
-  echo "**********************************************************"
-  echo -e "*  \033[31mCOMMIT ABORTED! Please address the errors before commiting.\033[0m"
-  echo "**********************************************************"
-  echo ""
+	err "COMMIT ABORTED! Please address the errors before commiting."
 fi
